### ISSUE TITLE
Backend/Server choices

### ISSUE THREAD

**Issue by igottheim** [umuthopeyildirim/FlatironSchoolOpenSource#12]
Will we use node.js for backend?

Will we use vercel/edge for server?

**Comment by umuthopeyildirim** [comment]
Not sure about Edge Config 👎🏻 

We can also try Cloudflare pages and their new database feature.
For Database: 
https://developers.cloudflare.com/d1/
https://developers.cloudflare.com/r2/
For Frontend:
https://developers.cloudflare.com/workers/

**Comment by umuthopeyildirim** [comment]
Decided with Cloudflare products.
