### ISSUE TITLE
Cleaning up Specific Course Pages

### ISSUE THREAD

**Issue by igottheim** [umuthopeyildirim/FlatironSchoolOpenSource#26]
For each course (SE, DS, DSAA) lets add a little description:

Click on each module to see classes:
Click each class to get the github repo:
Add a github logo(or similar) to show that it is a button with link.

Also check CSS styling on phone.

**Comment by umuthopeyildirim** [comment]
> For each course (SE, DS, DSAA) lets add a little description:

Are we going do this?

**Comment by umuthopeyildirim** [comment]
WE can re-open this issue in the future.
