### ISSUE TITLE
Create an react skin

### ISSUE THREAD

**Issue by umuthopeyildirim** [umuthopeyildirim/FlatironSchoolOpenSource#3]
This repo could use a react skin for easier use.

**Comment by umuthopeyildirim** [comment]
My idea for react skin, when I mean skin instead of using Canvas expored front-end we create our own front-end that works like Canvas.

*   [ ] Find a way to reverse engineer `course-data.js`
*   [ ] Create a front-end using tailwindcss and daisy-ui

**Comment by igottheim** [comment]
I'm in

**Comment by umuthopeyildirim** [comment]
Waiting for final approval.
