### ISSUE TITLE
Create Lessons page

### ISSUE THREAD

**Issue by umuthopeyildirim** [umuthopeyildirim/FlatironSchoolOpenSource#6]
List Lessons and show contents of game.
This will also add react-router, Still learning vite routing and we also need to decide on deployment site.
Cloudflare or Vercel?

**Comment by igottheim** [comment]
I've used Vercel in small doses, but I'm willing to try Cloudflare

**Comment by umuthopeyildirim** [comment]
> I've used Vercel in small doses, but I'm willing to try Cloudflare

Wanna switch one of your projects to cloudflare? It has to be node.js app though...

**Comment by igottheim** [comment]
yes I'm in
